server:
  port: 8082

spring:
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    jdbc-url: jdbc:mysql://127.0.0.1:3306/mtl?setUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 1
    maxActive: 10
    initialSize: 3
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'ZTM' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false 
    
    
mybatis: 
  mapperLocations: classpath*:com.zgc.mtl.dao/*Mapper.xml
  typeAliasesPackage: com.zgc.mtl.model
  configLocation: classpath:mybatis-config.xml