server:
  port: 8082
  servlet:  
   context-path: /mtl
  logging:
   config: classpath:log4j.properties

spring:
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/mtl?setUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 1
    maxActive: 10
    initialSize: 3
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'ZTM' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false 
    mvc:
    view:
    prefix: /
    suffix: .html
    
mybatis: 
  mapperLocations: classpath*:mapper/*.xml
  typeAliasesPackage: com.zgc.mtl.model
  configLocation: classpath:mybatis-config.xml