package com.zgc.mtl.mybatisGenerator.entity;

import java.io.Serializable;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class TInvestProfit implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_profit.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_profit.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_profit.profit_day
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date profitDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_profit.profit
     *
     * @mbg.generated
     */
    private Long profit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_profit.curr_total
     *
     * @mbg.generated
     */
    private Long currTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_profit.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_profit.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_profit.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_profit.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_invest_profit
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_profit.id
     *
     * @return the value of t_invest_profit.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_profit.id
     *
     * @param id the value for t_invest_profit.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_profit.order_id
     *
     * @return the value of t_invest_profit.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_profit.order_id
     *
     * @param orderId the value for t_invest_profit.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_profit.profit_day
     *
     * @return the value of t_invest_profit.profit_day
     *
     * @mbg.generated
     */
    public Date getProfitDay() {
        return profitDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_profit.profit_day
     *
     * @param profitDay the value for t_invest_profit.profit_day
     *
     * @mbg.generated
     */
    public void setProfitDay(Date profitDay) {
        this.profitDay = profitDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_profit.profit
     *
     * @return the value of t_invest_profit.profit
     *
     * @mbg.generated
     */
    public Long getProfit() {
        return profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_profit.profit
     *
     * @param profit the value for t_invest_profit.profit
     *
     * @mbg.generated
     */
    public void setProfit(Long profit) {
        this.profit = profit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_profit.curr_total
     *
     * @return the value of t_invest_profit.curr_total
     *
     * @mbg.generated
     */
    public Long getCurrTotal() {
        return currTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_profit.curr_total
     *
     * @param currTotal the value for t_invest_profit.curr_total
     *
     * @mbg.generated
     */
    public void setCurrTotal(Long currTotal) {
        this.currTotal = currTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_profit.create_time
     *
     * @return the value of t_invest_profit.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_profit.create_time
     *
     * @param createTime the value for t_invest_profit.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_profit.create_user
     *
     * @return the value of t_invest_profit.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_profit.create_user
     *
     * @param createUser the value for t_invest_profit.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_profit.update_time
     *
     * @return the value of t_invest_profit.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_profit.update_time
     *
     * @param updateTime the value for t_invest_profit.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_profit.update_user
     *
     * @return the value of t_invest_profit.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_profit.update_user
     *
     * @param updateUser the value for t_invest_profit.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_profit
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderId=").append(orderId);
        sb.append(", profitDay=").append(profitDay);
        sb.append(", profit=").append(profit);
        sb.append(", currTotal=").append(currTotal);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}