package com.zgc.mtl.mybatisGenerator.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TInvestOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    public TInvestOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andPrdIdIsNull() {
            addCriterion("prd_id is null");
            return (Criteria) this;
        }

        public Criteria andPrdIdIsNotNull() {
            addCriterion("prd_id is not null");
            return (Criteria) this;
        }

        public Criteria andPrdIdEqualTo(Integer value) {
            addCriterion("prd_id =", value, "prdId");
            return (Criteria) this;
        }

        public Criteria andPrdIdNotEqualTo(Integer value) {
            addCriterion("prd_id <>", value, "prdId");
            return (Criteria) this;
        }

        public Criteria andPrdIdGreaterThan(Integer value) {
            addCriterion("prd_id >", value, "prdId");
            return (Criteria) this;
        }

        public Criteria andPrdIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("prd_id >=", value, "prdId");
            return (Criteria) this;
        }

        public Criteria andPrdIdLessThan(Integer value) {
            addCriterion("prd_id <", value, "prdId");
            return (Criteria) this;
        }

        public Criteria andPrdIdLessThanOrEqualTo(Integer value) {
            addCriterion("prd_id <=", value, "prdId");
            return (Criteria) this;
        }

        public Criteria andPrdIdIn(List<Integer> values) {
            addCriterion("prd_id in", values, "prdId");
            return (Criteria) this;
        }

        public Criteria andPrdIdNotIn(List<Integer> values) {
            addCriterion("prd_id not in", values, "prdId");
            return (Criteria) this;
        }

        public Criteria andPrdIdBetween(Integer value1, Integer value2) {
            addCriterion("prd_id between", value1, value2, "prdId");
            return (Criteria) this;
        }

        public Criteria andPrdIdNotBetween(Integer value1, Integer value2) {
            addCriterion("prd_id not between", value1, value2, "prdId");
            return (Criteria) this;
        }

        public Criteria andPurchaseDateIsNull() {
            addCriterion("purchase_date is null");
            return (Criteria) this;
        }

        public Criteria andPurchaseDateIsNotNull() {
            addCriterion("purchase_date is not null");
            return (Criteria) this;
        }

        public Criteria andPurchaseDateEqualTo(Date value) {
            addCriterionForJDBCDate("purchase_date =", value, "purchaseDate");
            return (Criteria) this;
        }

        public Criteria andPurchaseDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("purchase_date <>", value, "purchaseDate");
            return (Criteria) this;
        }

        public Criteria andPurchaseDateGreaterThan(Date value) {
            addCriterionForJDBCDate("purchase_date >", value, "purchaseDate");
            return (Criteria) this;
        }

        public Criteria andPurchaseDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("purchase_date >=", value, "purchaseDate");
            return (Criteria) this;
        }

        public Criteria andPurchaseDateLessThan(Date value) {
            addCriterionForJDBCDate("purchase_date <", value, "purchaseDate");
            return (Criteria) this;
        }

        public Criteria andPurchaseDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("purchase_date <=", value, "purchaseDate");
            return (Criteria) this;
        }

        public Criteria andPurchaseDateIn(List<Date> values) {
            addCriterionForJDBCDate("purchase_date in", values, "purchaseDate");
            return (Criteria) this;
        }

        public Criteria andPurchaseDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("purchase_date not in", values, "purchaseDate");
            return (Criteria) this;
        }

        public Criteria andPurchaseDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("purchase_date between", value1, value2, "purchaseDate");
            return (Criteria) this;
        }

        public Criteria andPurchaseDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("purchase_date not between", value1, value2, "purchaseDate");
            return (Criteria) this;
        }

        public Criteria andPurchaseQuotaIsNull() {
            addCriterion("purchase_quota is null");
            return (Criteria) this;
        }

        public Criteria andPurchaseQuotaIsNotNull() {
            addCriterion("purchase_quota is not null");
            return (Criteria) this;
        }

        public Criteria andPurchaseQuotaEqualTo(Long value) {
            addCriterion("purchase_quota =", value, "purchaseQuota");
            return (Criteria) this;
        }

        public Criteria andPurchaseQuotaNotEqualTo(Long value) {
            addCriterion("purchase_quota <>", value, "purchaseQuota");
            return (Criteria) this;
        }

        public Criteria andPurchaseQuotaGreaterThan(Long value) {
            addCriterion("purchase_quota >", value, "purchaseQuota");
            return (Criteria) this;
        }

        public Criteria andPurchaseQuotaGreaterThanOrEqualTo(Long value) {
            addCriterion("purchase_quota >=", value, "purchaseQuota");
            return (Criteria) this;
        }

        public Criteria andPurchaseQuotaLessThan(Long value) {
            addCriterion("purchase_quota <", value, "purchaseQuota");
            return (Criteria) this;
        }

        public Criteria andPurchaseQuotaLessThanOrEqualTo(Long value) {
            addCriterion("purchase_quota <=", value, "purchaseQuota");
            return (Criteria) this;
        }

        public Criteria andPurchaseQuotaIn(List<Long> values) {
            addCriterion("purchase_quota in", values, "purchaseQuota");
            return (Criteria) this;
        }

        public Criteria andPurchaseQuotaNotIn(List<Long> values) {
            addCriterion("purchase_quota not in", values, "purchaseQuota");
            return (Criteria) this;
        }

        public Criteria andPurchaseQuotaBetween(Long value1, Long value2) {
            addCriterion("purchase_quota between", value1, value2, "purchaseQuota");
            return (Criteria) this;
        }

        public Criteria andPurchaseQuotaNotBetween(Long value1, Long value2) {
            addCriterion("purchase_quota not between", value1, value2, "purchaseQuota");
            return (Criteria) this;
        }

        public Criteria andProfitBeginIsNull() {
            addCriterion("profit_begin is null");
            return (Criteria) this;
        }

        public Criteria andProfitBeginIsNotNull() {
            addCriterion("profit_begin is not null");
            return (Criteria) this;
        }

        public Criteria andProfitBeginEqualTo(Date value) {
            addCriterionForJDBCDate("profit_begin =", value, "profitBegin");
            return (Criteria) this;
        }

        public Criteria andProfitBeginNotEqualTo(Date value) {
            addCriterionForJDBCDate("profit_begin <>", value, "profitBegin");
            return (Criteria) this;
        }

        public Criteria andProfitBeginGreaterThan(Date value) {
            addCriterionForJDBCDate("profit_begin >", value, "profitBegin");
            return (Criteria) this;
        }

        public Criteria andProfitBeginGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("profit_begin >=", value, "profitBegin");
            return (Criteria) this;
        }

        public Criteria andProfitBeginLessThan(Date value) {
            addCriterionForJDBCDate("profit_begin <", value, "profitBegin");
            return (Criteria) this;
        }

        public Criteria andProfitBeginLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("profit_begin <=", value, "profitBegin");
            return (Criteria) this;
        }

        public Criteria andProfitBeginIn(List<Date> values) {
            addCriterionForJDBCDate("profit_begin in", values, "profitBegin");
            return (Criteria) this;
        }

        public Criteria andProfitBeginNotIn(List<Date> values) {
            addCriterionForJDBCDate("profit_begin not in", values, "profitBegin");
            return (Criteria) this;
        }

        public Criteria andProfitBeginBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("profit_begin between", value1, value2, "profitBegin");
            return (Criteria) this;
        }

        public Criteria andProfitBeginNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("profit_begin not between", value1, value2, "profitBegin");
            return (Criteria) this;
        }

        public Criteria andExpireDateIsNull() {
            addCriterion("expire_date is null");
            return (Criteria) this;
        }

        public Criteria andExpireDateIsNotNull() {
            addCriterion("expire_date is not null");
            return (Criteria) this;
        }

        public Criteria andExpireDateEqualTo(Date value) {
            addCriterionForJDBCDate("expire_date =", value, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("expire_date <>", value, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateGreaterThan(Date value) {
            addCriterionForJDBCDate("expire_date >", value, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("expire_date >=", value, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateLessThan(Date value) {
            addCriterionForJDBCDate("expire_date <", value, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("expire_date <=", value, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateIn(List<Date> values) {
            addCriterionForJDBCDate("expire_date in", values, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("expire_date not in", values, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("expire_date between", value1, value2, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("expire_date not between", value1, value2, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExtractDateIsNull() {
            addCriterion("\"extract date\" is null");
            return (Criteria) this;
        }

        public Criteria andExtractDateIsNotNull() {
            addCriterion("\"extract date\" is not null");
            return (Criteria) this;
        }

        public Criteria andExtractDateEqualTo(Date value) {
            addCriterionForJDBCDate("\"extract date\" =", value, "extractDate");
            return (Criteria) this;
        }

        public Criteria andExtractDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("\"extract date\" <>", value, "extractDate");
            return (Criteria) this;
        }

        public Criteria andExtractDateGreaterThan(Date value) {
            addCriterionForJDBCDate("\"extract date\" >", value, "extractDate");
            return (Criteria) this;
        }

        public Criteria andExtractDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("\"extract date\" >=", value, "extractDate");
            return (Criteria) this;
        }

        public Criteria andExtractDateLessThan(Date value) {
            addCriterionForJDBCDate("\"extract date\" <", value, "extractDate");
            return (Criteria) this;
        }

        public Criteria andExtractDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("\"extract date\" <=", value, "extractDate");
            return (Criteria) this;
        }

        public Criteria andExtractDateIn(List<Date> values) {
            addCriterionForJDBCDate("\"extract date\" in", values, "extractDate");
            return (Criteria) this;
        }

        public Criteria andExtractDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("\"extract date\" not in", values, "extractDate");
            return (Criteria) this;
        }

        public Criteria andExtractDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("\"extract date\" between", value1, value2, "extractDate");
            return (Criteria) this;
        }

        public Criteria andExtractDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("\"extract date\" not between", value1, value2, "extractDate");
            return (Criteria) this;
        }

        public Criteria andExtractDescriptionIsNull() {
            addCriterion("extract_description is null");
            return (Criteria) this;
        }

        public Criteria andExtractDescriptionIsNotNull() {
            addCriterion("extract_description is not null");
            return (Criteria) this;
        }

        public Criteria andExtractDescriptionEqualTo(String value) {
            addCriterion("extract_description =", value, "extractDescription");
            return (Criteria) this;
        }

        public Criteria andExtractDescriptionNotEqualTo(String value) {
            addCriterion("extract_description <>", value, "extractDescription");
            return (Criteria) this;
        }

        public Criteria andExtractDescriptionGreaterThan(String value) {
            addCriterion("extract_description >", value, "extractDescription");
            return (Criteria) this;
        }

        public Criteria andExtractDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("extract_description >=", value, "extractDescription");
            return (Criteria) this;
        }

        public Criteria andExtractDescriptionLessThan(String value) {
            addCriterion("extract_description <", value, "extractDescription");
            return (Criteria) this;
        }

        public Criteria andExtractDescriptionLessThanOrEqualTo(String value) {
            addCriterion("extract_description <=", value, "extractDescription");
            return (Criteria) this;
        }

        public Criteria andExtractDescriptionLike(String value) {
            addCriterion("extract_description like", value, "extractDescription");
            return (Criteria) this;
        }

        public Criteria andExtractDescriptionNotLike(String value) {
            addCriterion("extract_description not like", value, "extractDescription");
            return (Criteria) this;
        }

        public Criteria andExtractDescriptionIn(List<String> values) {
            addCriterion("extract_description in", values, "extractDescription");
            return (Criteria) this;
        }

        public Criteria andExtractDescriptionNotIn(List<String> values) {
            addCriterion("extract_description not in", values, "extractDescription");
            return (Criteria) this;
        }

        public Criteria andExtractDescriptionBetween(String value1, String value2) {
            addCriterion("extract_description between", value1, value2, "extractDescription");
            return (Criteria) this;
        }

        public Criteria andExtractDescriptionNotBetween(String value1, String value2) {
            addCriterion("extract_description not between", value1, value2, "extractDescription");
            return (Criteria) this;
        }

        public Criteria andExtractModeIsNull() {
            addCriterion("extract_mode is null");
            return (Criteria) this;
        }

        public Criteria andExtractModeIsNotNull() {
            addCriterion("extract_mode is not null");
            return (Criteria) this;
        }

        public Criteria andExtractModeEqualTo(String value) {
            addCriterion("extract_mode =", value, "extractMode");
            return (Criteria) this;
        }

        public Criteria andExtractModeNotEqualTo(String value) {
            addCriterion("extract_mode <>", value, "extractMode");
            return (Criteria) this;
        }

        public Criteria andExtractModeGreaterThan(String value) {
            addCriterion("extract_mode >", value, "extractMode");
            return (Criteria) this;
        }

        public Criteria andExtractModeGreaterThanOrEqualTo(String value) {
            addCriterion("extract_mode >=", value, "extractMode");
            return (Criteria) this;
        }

        public Criteria andExtractModeLessThan(String value) {
            addCriterion("extract_mode <", value, "extractMode");
            return (Criteria) this;
        }

        public Criteria andExtractModeLessThanOrEqualTo(String value) {
            addCriterion("extract_mode <=", value, "extractMode");
            return (Criteria) this;
        }

        public Criteria andExtractModeLike(String value) {
            addCriterion("extract_mode like", value, "extractMode");
            return (Criteria) this;
        }

        public Criteria andExtractModeNotLike(String value) {
            addCriterion("extract_mode not like", value, "extractMode");
            return (Criteria) this;
        }

        public Criteria andExtractModeIn(List<String> values) {
            addCriterion("extract_mode in", values, "extractMode");
            return (Criteria) this;
        }

        public Criteria andExtractModeNotIn(List<String> values) {
            addCriterion("extract_mode not in", values, "extractMode");
            return (Criteria) this;
        }

        public Criteria andExtractModeBetween(String value1, String value2) {
            addCriterion("extract_mode between", value1, value2, "extractMode");
            return (Criteria) this;
        }

        public Criteria andExtractModeNotBetween(String value1, String value2) {
            addCriterion("extract_mode not between", value1, value2, "extractMode");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_invest_order
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}