package com.zgc.mtl.mybatisGenerator.entity;

import java.io.Serializable;
import java.util.Date;

public class TInvestOrder implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_order.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_order.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_order.prd_id
     *
     * @mbg.generated
     */
    private Integer prdId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_order.purchase_date
     *
     * @mbg.generated
     */
    private Date purchaseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_order.purchase_quota
     *
     * @mbg.generated
     */
    private Long purchaseQuota;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_order.profit_begin
     *
     * @mbg.generated
     */
    private Date profitBegin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_order.expire_date
     *
     * @mbg.generated
     */
    private Date expireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_order.extract date
     *
     * @mbg.generated
     */
    private Date extractDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_order.extract_description
     *
     * @mbg.generated
     */
    private String extractDescription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_order.extract_mode
     *
     * @mbg.generated
     */
    private String extractMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_order.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_order.create_user
     *
     * @mbg.generated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_order.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_invest_order.update_user
     *
     * @mbg.generated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_order.order_id
     *
     * @return the value of t_invest_order.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_order.order_id
     *
     * @param orderId the value for t_invest_order.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_order.user_id
     *
     * @return the value of t_invest_order.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_order.user_id
     *
     * @param userId the value for t_invest_order.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_order.prd_id
     *
     * @return the value of t_invest_order.prd_id
     *
     * @mbg.generated
     */
    public Integer getPrdId() {
        return prdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_order.prd_id
     *
     * @param prdId the value for t_invest_order.prd_id
     *
     * @mbg.generated
     */
    public void setPrdId(Integer prdId) {
        this.prdId = prdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_order.purchase_date
     *
     * @return the value of t_invest_order.purchase_date
     *
     * @mbg.generated
     */
    public Date getPurchaseDate() {
        return purchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_order.purchase_date
     *
     * @param purchaseDate the value for t_invest_order.purchase_date
     *
     * @mbg.generated
     */
    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_order.purchase_quota
     *
     * @return the value of t_invest_order.purchase_quota
     *
     * @mbg.generated
     */
    public Long getPurchaseQuota() {
        return purchaseQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_order.purchase_quota
     *
     * @param purchaseQuota the value for t_invest_order.purchase_quota
     *
     * @mbg.generated
     */
    public void setPurchaseQuota(Long purchaseQuota) {
        this.purchaseQuota = purchaseQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_order.profit_begin
     *
     * @return the value of t_invest_order.profit_begin
     *
     * @mbg.generated
     */
    public Date getProfitBegin() {
        return profitBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_order.profit_begin
     *
     * @param profitBegin the value for t_invest_order.profit_begin
     *
     * @mbg.generated
     */
    public void setProfitBegin(Date profitBegin) {
        this.profitBegin = profitBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_order.expire_date
     *
     * @return the value of t_invest_order.expire_date
     *
     * @mbg.generated
     */
    public Date getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_order.expire_date
     *
     * @param expireDate the value for t_invest_order.expire_date
     *
     * @mbg.generated
     */
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_order.extract date
     *
     * @return the value of t_invest_order.extract date
     *
     * @mbg.generated
     */
    public Date getExtractDate() {
        return extractDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_order.extract date
     *
     * @param extractDate the value for t_invest_order.extract date
     *
     * @mbg.generated
     */
    public void setExtractDate(Date extractDate) {
        this.extractDate = extractDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_order.extract_description
     *
     * @return the value of t_invest_order.extract_description
     *
     * @mbg.generated
     */
    public String getExtractDescription() {
        return extractDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_order.extract_description
     *
     * @param extractDescription the value for t_invest_order.extract_description
     *
     * @mbg.generated
     */
    public void setExtractDescription(String extractDescription) {
        this.extractDescription = extractDescription == null ? null : extractDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_order.extract_mode
     *
     * @return the value of t_invest_order.extract_mode
     *
     * @mbg.generated
     */
    public String getExtractMode() {
        return extractMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_order.extract_mode
     *
     * @param extractMode the value for t_invest_order.extract_mode
     *
     * @mbg.generated
     */
    public void setExtractMode(String extractMode) {
        this.extractMode = extractMode == null ? null : extractMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_order.create_time
     *
     * @return the value of t_invest_order.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_order.create_time
     *
     * @param createTime the value for t_invest_order.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_order.create_user
     *
     * @return the value of t_invest_order.create_user
     *
     * @mbg.generated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_order.create_user
     *
     * @param createUser the value for t_invest_order.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_order.update_time
     *
     * @return the value of t_invest_order.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_order.update_time
     *
     * @param updateTime the value for t_invest_order.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_invest_order.update_user
     *
     * @return the value of t_invest_order.update_user
     *
     * @mbg.generated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_invest_order.update_user
     *
     * @param updateUser the value for t_invest_order.update_user
     *
     * @mbg.generated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderId=").append(orderId);
        sb.append(", userId=").append(userId);
        sb.append(", prdId=").append(prdId);
        sb.append(", purchaseDate=").append(purchaseDate);
        sb.append(", purchaseQuota=").append(purchaseQuota);
        sb.append(", profitBegin=").append(profitBegin);
        sb.append(", expireDate=").append(expireDate);
        sb.append(", extractDate=").append(extractDate);
        sb.append(", extractDescription=").append(extractDescription);
        sb.append(", extractMode=").append(extractMode);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}