package com.zgc.mtl.mybatisGenerator.dao;

import com.zgc.mtl.mybatisGenerator.entity.BaseSex;
import com.zgc.mtl.mybatisGenerator.entity.BaseSexExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BaseSexMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sex
     *
     * @mbg.generated
     */
    long countByExample(BaseSexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sex
     *
     * @mbg.generated
     */
    int deleteByExample(BaseSexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sex
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String sexId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sex
     *
     * @mbg.generated
     */
    int insert(BaseSex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sex
     *
     * @mbg.generated
     */
    int insertSelective(BaseSex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sex
     *
     * @mbg.generated
     */
    List<BaseSex> selectByExample(BaseSexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sex
     *
     * @mbg.generated
     */
    BaseSex selectByPrimaryKey(String sexId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sex
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BaseSex record, @Param("example") BaseSexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sex
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BaseSex record, @Param("example") BaseSexExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sex
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BaseSex record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_sex
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BaseSex record);
}