package com.zgc.mtl.mybatisGenerator.dao;

import com.zgc.mtl.mybatisGenerator.entity.THealthy;
import com.zgc.mtl.mybatisGenerator.entity.THealthyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface THealthyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_healthy
     *
     * @mbg.generated
     */
    long countByExample(THealthyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_healthy
     *
     * @mbg.generated
     */
    int deleteByExample(THealthyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_healthy
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_healthy
     *
     * @mbg.generated
     */
    int insert(THealthy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_healthy
     *
     * @mbg.generated
     */
    int insertSelective(THealthy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_healthy
     *
     * @mbg.generated
     */
    List<THealthy> selectByExample(THealthyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_healthy
     *
     * @mbg.generated
     */
    THealthy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_healthy
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") THealthy record, @Param("example") THealthyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_healthy
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") THealthy record, @Param("example") THealthyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_healthy
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(THealthy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_healthy
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(THealthy record);
}