package com.zgc.mtl.mybatisGenerator.dao;

import com.zgc.mtl.mybatisGenerator.entity.TInvestProfit;
import com.zgc.mtl.mybatisGenerator.entity.TInvestProfitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TInvestProfitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_profit
     *
     * @mbg.generated
     */
    long countByExample(TInvestProfitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_profit
     *
     * @mbg.generated
     */
    int deleteByExample(TInvestProfitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_profit
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_profit
     *
     * @mbg.generated
     */
    int insert(TInvestProfit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_profit
     *
     * @mbg.generated
     */
    int insertSelective(TInvestProfit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_profit
     *
     * @mbg.generated
     */
    List<TInvestProfit> selectByExample(TInvestProfitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_profit
     *
     * @mbg.generated
     */
    TInvestProfit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_profit
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TInvestProfit record, @Param("example") TInvestProfitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_profit
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TInvestProfit record, @Param("example") TInvestProfitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_profit
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TInvestProfit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_profit
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TInvestProfit record);
}