package com.zgc.mtl.mybatisGenerator.dao;

import com.zgc.mtl.mybatisGenerator.entity.TInvestOrder;
import com.zgc.mtl.mybatisGenerator.entity.TInvestOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TInvestOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    long countByExample(TInvestOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    int deleteByExample(TInvestOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    int insert(TInvestOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    int insertSelective(TInvestOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    List<TInvestOrder> selectByExample(TInvestOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    TInvestOrder selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TInvestOrder record, @Param("example") TInvestOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TInvestOrder record, @Param("example") TInvestOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TInvestOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TInvestOrder record);
}