package com.zgc.mtl.mybatisGenerator.dao;

import com.zgc.mtl.mybatisGenerator.entity.TInvestProduct;
import com.zgc.mtl.mybatisGenerator.entity.TInvestProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TInvestProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_product
     *
     * @mbg.generated
     */
    long countByExample(TInvestProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_product
     *
     * @mbg.generated
     */
    int deleteByExample(TInvestProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer prdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_product
     *
     * @mbg.generated
     */
    int insert(TInvestProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_product
     *
     * @mbg.generated
     */
    int insertSelective(TInvestProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_product
     *
     * @mbg.generated
     */
    List<TInvestProduct> selectByExample(TInvestProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_product
     *
     * @mbg.generated
     */
    TInvestProduct selectByPrimaryKey(Integer prdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TInvestProduct record, @Param("example") TInvestProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TInvestProduct record, @Param("example") TInvestProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TInvestProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TInvestProduct record);
}