package com.zgc.mtl.mybatisGenerator.dao;

import com.zgc.mtl.mybatisGenerator.entity.TInvestUser;
import com.zgc.mtl.mybatisGenerator.entity.TInvestUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TInvestUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_user
     *
     * @mbg.generated
     */
    long countByExample(TInvestUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_user
     *
     * @mbg.generated
     */
    int deleteByExample(TInvestUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_user
     *
     * @mbg.generated
     */
    int insert(TInvestUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_user
     *
     * @mbg.generated
     */
    int insertSelective(TInvestUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_user
     *
     * @mbg.generated
     */
    List<TInvestUser> selectByExample(TInvestUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_user
     *
     * @mbg.generated
     */
    TInvestUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TInvestUser record, @Param("example") TInvestUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TInvestUser record, @Param("example") TInvestUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TInvestUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TInvestUser record);
}