package com.zgc.mtl.mybatisGenerator.dao;

import com.zgc.mtl.mybatisGenerator.entity.TInvestType;
import com.zgc.mtl.mybatisGenerator.entity.TInvestTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TInvestTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_type
     *
     * @mbg.generated
     */
    long countByExample(TInvestTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_type
     *
     * @mbg.generated
     */
    int deleteByExample(TInvestTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_type
     *
     * @mbg.generated
     */
    int insert(TInvestType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_type
     *
     * @mbg.generated
     */
    int insertSelective(TInvestType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_type
     *
     * @mbg.generated
     */
    List<TInvestType> selectByExample(TInvestTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_type
     *
     * @mbg.generated
     */
    TInvestType selectByPrimaryKey(String typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TInvestType record, @Param("example") TInvestTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TInvestType record, @Param("example") TInvestTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TInvestType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_invest_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TInvestType record);
}